demo:
  var: This is PROD environment.
server:
  port: 8010
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
#management:
#  security:
#    enabled: false