demo:
  var: This is DEV environment.
server:
  port: 8010
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
spring:
  zipkin:
    base-url: http://localhost:8070/
#management:
#  security:
#    enabled: false