server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
zuul:
  sensitive-headers: Cookie,Set-Cookie
  ignoredServices: '*'
  routes:
    main-service:
      path: /**
    hystrix-dashboard:
      path: /hystrix/**
      stripPrefix: false
    hystrix-dashboard-webjars:
      path: /webjars/d3js/**
      serviceId: hystrix-dashboard
      stripPrefix: false
    hystrix-dashboard-proxystream:
      path: /proxy.stream
      serviceId: hystrix-dashboard
      stripPrefix: false
    service-one:
      path: /getTime